name: Build

on:
  push:
  pull_request:

jobs:
  build:
    name: Build Firmware
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          path: app  # needed to pass the repo as a manifest repo to Zephyr setup action

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'
      
      - name: Setup Zephyr project
        uses: zephyrproject-rtos/action-zephyr-setup@v1
        with:
          app-path: app  # as configured in the checkout step
          toolchains: arm-zephyr-eabi

      - name: Build project
        shell: bash
        run: |
          west build app/app -b bap6000 -p auto
